/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazProyecto;

import com.mycompany.proyectoclienteservidor.Actividad;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andre
 */
public class Actividades extends javax.swing.JFrame {

    /**
     * Creates new form Actividades
     */
    
    DefaultTableModel mt = new DefaultTableModel();
    public Actividades() {
        initComponents();
        String sqlActividades = "SELECT * FROM t_actividades";
        
        Connection nuevaConexion; 
        
        
        
        
        // Paises
        try {
            nuevaConexion = DriverManager.getConnection("jdbc:mysql://localhost/paises?serverTimezone=UTC", "root","Rojo2001.");

        Statement st;
        String ids[] = {"Pais","Actividad", "Precio","Fecha"};
        mt.setColumnIdentifiers(ids);
        
        jTable3.setModel(mt);
        
        String[] dato = new String[4];
        
            st = nuevaConexion.createStatement();
            
            ResultSet result = st.executeQuery(sqlActividades);
            
            while(result.next()){
                dato[0]= result.getString(2);
                dato[1]= result.getString(3);
                dato[2]= result.getString(4);
                dato[3]= result.getString(5);
                
                
                mt.addRow(dato);
            }
        } catch (SQLException ex) {
            Logger.getLogger(HomeAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        txtActividadesPais = new javax.swing.JTextField();
        lblPaisAgregar3 = new javax.swing.JLabel();
        txtActividadActividades = new javax.swing.JTextField();
        lblTipoAgregar3 = new javax.swing.JLabel();
        txtPrecioActividades = new javax.swing.JTextField();
        lblPrecioAgregar3 = new javax.swing.JLabel();
        lblFechaAgregar3 = new javax.swing.JLabel();
        txtFechaActividades = new javax.swing.JTextField();
        btnCerrarAlojamiento2 = new javax.swing.JButton();
        btnBorrarActividades = new javax.swing.JButton();
        btnActualizarActividades = new javax.swing.JButton();
        btnAgregarActividades = new javax.swing.JButton();
        txtIDActividades = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("¡Bienvenido Admin!");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Pais", "Ciudad", "Precio", "Cantidad de Personas"
            }
        ));
        jScrollPane2.setViewportView(jTable3);

        txtActividadesPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActividadesPaisActionPerformed(evt);
            }
        });

        lblPaisAgregar3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPaisAgregar3.setText("Pais");

        lblTipoAgregar3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTipoAgregar3.setText("Actividad");

        lblPrecioAgregar3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrecioAgregar3.setText("Precio");

        lblFechaAgregar3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFechaAgregar3.setText("Fecha");

        txtFechaActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActividadesActionPerformed(evt);
            }
        });

        btnCerrarAlojamiento2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrarAlojamiento2.setText("Cerrar");

        btnBorrarActividades.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBorrarActividades.setText("Borrar");
        btnBorrarActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActividadesActionPerformed(evt);
            }
        });

        btnActualizarActividades.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizarActividades.setText("Actualizar");
        btnActualizarActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActividadesActionPerformed(evt);
            }
        });

        btnAgregarActividades.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarActividades.setText("Agregar");
        btnAgregarActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActividadesActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(21, 21, 21)
                                            .addComponent(lblPaisAgregar3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(txtActividadesPais, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(47, 47, 47)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTipoAgregar3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtActividadActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnActualizarActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(btnAgregarActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtIDActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(37, 37, 37)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPrecioAgregar3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPrecioActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBorrarActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnCerrarAlojamiento2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFechaActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblFechaAgregar3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaisAgregar3)
                    .addComponent(lblTipoAgregar3)
                    .addComponent(lblPrecioAgregar3)
                    .addComponent(lblFechaAgregar3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtActividadesPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtActividadActividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaActividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecioActividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarActividades)
                    .addComponent(btnAgregarActividades)
                    .addComponent(btnBorrarActividades)
                    .addComponent(btnCerrarAlojamiento2))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDActividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtActividadesPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActividadesPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtActividadesPaisActionPerformed

    private void txtFechaActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActividadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActividadesActionPerformed

    private void btnBorrarActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActividadesActionPerformed
        try {
            Connection nuevaConexion = DriverManager.getConnection("jdbc:mysql://localhost/paises?serverTimezone=UTC", "root","Rojo2001.");

            String comando_delete = "DELETE FROM t_actividades  WHERE id = ?";

            PreparedStatement comandoPreparado = nuevaConexion.prepareStatement(comando_delete);

            // comandoPreparado.setString(1,txtIDActualizar.getText());
            comandoPreparado.setInt(1, Integer.parseInt(txtIDActividades.getText()));

            comandoPreparado.executeUpdate();

            int fila = Integer.parseInt(txtIDActividades.getText());

            mt.removeRow(fila-1);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al conectar con la Base de Datos "+ex.getMessage());
        }
    }//GEN-LAST:event_btnBorrarActividadesActionPerformed

    private void btnActualizarActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActividadesActionPerformed
        try {
            Connection nuevaConexion = DriverManager.getConnection("jdbc:mysql://localhost/paises?serverTimezone=UTC", "root","Rojo2001.");

            String comando_update = "UPDATE t_actividades SET  pais=?, actividad = ?,precio = ?, fecha = ? WHERE id = ?";

            PreparedStatement comandoPreparado = nuevaConexion.prepareStatement(comando_update);

            // comandoPreparado.setString(1,txtIDActualizar.getText());
            comandoPreparado.setString(1, txtActividadesPais.getText());
            comandoPreparado.setString(2, txtActividadActividades.getText());
            comandoPreparado.setDouble(3, Double.parseDouble(txtPrecioActividades.getText()));
            comandoPreparado.setString(4, txtFechaActividades.getText());

            comandoPreparado.setInt(5,Integer.parseInt(txtIDActividades.getText()));

            comandoPreparado.executeUpdate();

            int fila = Integer.parseInt(txtIDActividades.getText());

            mt.setValueAt(txtActividadesPais.getText(),fila-1,0 );
            mt.setValueAt(txtActividadActividades.getText(),fila-1,1 );
            mt.setValueAt(Double.parseDouble(txtPrecioActividades.getText()),fila-1,2 );
            mt.setValueAt(txtFechaActividades.getText(),fila-1,3 );

            txtActividadesPais.setText("");
            txtActividadActividades.setText("");
            txtPrecioActividades.setText("");
            txtFechaActividades.setText("");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al conectar con la Base de Datos "+ex.getMessage());
        }
    }//GEN-LAST:event_btnActualizarActividadesActionPerformed

    private void btnAgregarActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActividadesActionPerformed
        Actividad alojamiento = new Actividad();

        alojamiento.setPais(txtActividadesPais.getText());
        alojamiento.setActividad(txtActividadActividades.getText());
        alojamiento.setPrecio(Double.parseDouble(txtPrecioActividades.getText()));
        alojamiento.setFecha(txtFechaActividades.getText());

        mt.addRow(new Object[]{alojamiento.getPais(), alojamiento.getActividad(), alojamiento.getPrecio(), alojamiento.getFecha()});
        txtActividadesPais.setText("");
        txtActividadActividades.setText("");
        txtPrecioActividades.setText("");
        txtFechaActividades.setText("");

        //BASES DE DATOS
        try{
            Connection nuevaConexion = DriverManager.getConnection("jdbc:mysql://localhost/paises?serverTimezone=UTC", "root","Rojo2001.");
            String comando = "INSERT INTO t_actividades( pais, actividad, precio, fecha)"
            + "VALUES(?,?,?,?)";

            PreparedStatement comandoPreparado = nuevaConexion.prepareStatement(comando);

            comandoPreparado.setString(1, alojamiento.getPais());
            comandoPreparado.setString(2, alojamiento.getActividad());
            comandoPreparado.setDouble(3, alojamiento.getPrecio());
            comandoPreparado.setString(4, alojamiento.getFecha());

            comandoPreparado.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al conectar con la Base de Datos "+ex.getMessage());

        }
    }//GEN-LAST:event_btnAgregarActividadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actividades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarActividades;
    private javax.swing.JButton btnAgregarActividades;
    private javax.swing.JButton btnBorrarActividades;
    private javax.swing.JButton btnCerrarAlojamiento2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel lblFechaAgregar3;
    private javax.swing.JLabel lblPaisAgregar3;
    private javax.swing.JLabel lblPrecioAgregar3;
    private javax.swing.JLabel lblTipoAgregar3;
    private javax.swing.JTextField txtActividadActividades;
    private javax.swing.JTextField txtActividadesPais;
    private javax.swing.JTextField txtFechaActividades;
    private javax.swing.JTextField txtIDActividades;
    private javax.swing.JTextField txtPrecioActividades;
    // End of variables declaration//GEN-END:variables
}
