/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazProyecto;

import com.mycompany.proyectoclienteservidor.Pais;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author andre
 */


public class HomeAdmin extends javax.swing.JFrame {
    DefaultTableModel mt = new DefaultTableModel();
    
    /**
     * Creates new form test
     */
    public HomeAdmin() {
        initComponents();
        
        String sqlPaises = "SELECT * FROM t_paises";
        //String sqlAlojamientos = "SELECT * FROM t_alojamientos";
        Connection nuevaConexion; 
        
        
        
        
        // Paises
        try {
            nuevaConexion = DriverManager.getConnection("jdbc:mysql://localhost/paises?serverTimezone=UTC", "root","Rojo2001.");

        Statement st;
        String ids[] = {"Pais","Tipo", "Precio","Fecha"};
        mt.setColumnIdentifiers(ids);
        
        jTable1.setModel(mt);
        
        String[] dato = new String[4];
        
            st = nuevaConexion.createStatement();
            
            ResultSet result = st.executeQuery(sqlPaises);
            
            while(result.next()){
                dato[0]= result.getString(2);
                dato[1]= result.getString(3);
                dato[2]= result.getString(4);
                dato[3]= result.getString(5);
                
                
                mt.addRow(dato);
            }
        } catch (SQLException ex) {
            Logger.getLogger(HomeAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }
    /**
     * Creates new form test
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblPaisAgregar = new javax.swing.JLabel();
        txtPaisAgregar = new javax.swing.JTextField();
        lblTipoAgregar = new javax.swing.JLabel();
        txtPrecioAgregar = new javax.swing.JTextField();
        txtFechaAgregar = new javax.swing.JTextField();
        lblPrecioAgregar = new javax.swing.JLabel();
        lblFechaAgregar = new javax.swing.JLabel();
        cboxTipoAgregar = new javax.swing.JComboBox<>();
        btnActualizarPais = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnAgregarPais = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        txtIDActualizar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("¡Bienvenido Admin!");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Pais", "Tipo", "Precio", "Fecha"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lblPaisAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPaisAgregar.setText("Pais");

        lblTipoAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTipoAgregar.setText("Tipo");

        lblPrecioAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrecioAgregar.setText("Precio");

        lblFechaAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFechaAgregar.setText("Fecha");

        cboxTipoAgregar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aventura", "Relajacion", "Cultural", " " }));

        btnActualizarPais.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizarPais.setText("Actualizar");
        btnActualizarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPaisActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("Cerrar");

        btnAgregarPais.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarPais.setText("Agregar");
        btnAgregarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPaisActionPerformed(evt);
            }
        });

        btnBorrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPaisAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPaisAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(lblTipoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnActualizarPais, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cboxTipoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(btnAgregarPais, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecioAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecioAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecioAgregar)
                            .addComponent(lblFechaAgregar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecioAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPaisAgregar)
                            .addComponent(lblTipoAgregar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPaisAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxTipoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(btnActualizarPais)
                    .addComponent(btnAgregarPais)
                    .addComponent(btnBorrar))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Paises", jPanel1);

        jLabel2.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIDActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed

        try {
            Connection nuevaConexion = DriverManager.getConnection("jdbc:mysql://localhost/paises?serverTimezone=UTC", "root","Rojo2001.");

            String comando_delete = "DELETE FROM t_paises  WHERE id = ?";

            PreparedStatement comandoPreparado = nuevaConexion.prepareStatement(comando_delete);

            // comandoPreparado.setString(1,txtIDActualizar.getText());
            comandoPreparado.setInt(1, Integer.parseInt(txtIDActualizar.getText()));

            comandoPreparado.executeUpdate();

            int fila = Integer.parseInt(txtIDActualizar.getText());

            mt.removeRow(fila-1);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al conectar con la Base de Datos "+ex.getMessage());
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnAgregarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPaisActionPerformed
        Pais pais = new Pais();

        pais.setUbicacion(txtPaisAgregar.getText());
        pais.setTipoViaje((String) cboxTipoAgregar.getSelectedItem());
        pais.setPrecio(Double.parseDouble(txtPrecioAgregar.getText()));
        pais.setFecha(txtFechaAgregar.getText());

        mt.addRow(new Object[]{pais.getUbicacion(), pais.getTipoViaje(), pais.getPresupuesto(), pais.getFecha()});
        txtPaisAgregar.setText("");
        txtPrecioAgregar.setText("");
        txtFechaAgregar.setText("");

        //BASES DE DATOS
        try{
            Connection nuevaConexion = DriverManager.getConnection("jdbc:mysql://localhost/paises?serverTimezone=UTC", "root","Rojo2001.");
            String comando = "INSERT INTO t_paises( pais, tipo, precio, fecha)"
            + "VALUES(?,?,?,?)";

            PreparedStatement comandoPreparado = nuevaConexion.prepareStatement(comando);

            comandoPreparado.setString(1, pais.getUbicacion());
            comandoPreparado.setString(2, pais.getTipoViaje());
            comandoPreparado.setDouble(3, pais.getPresupuesto());
            comandoPreparado.setString(4, pais.getFecha());

            comandoPreparado.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al conectar con la Base de Datos "+ex.getMessage());

        }

    }//GEN-LAST:event_btnAgregarPaisActionPerformed

    private void btnActualizarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPaisActionPerformed

        try {
            Connection nuevaConexion = DriverManager.getConnection("jdbc:mysql://localhost/paises?serverTimezone=UTC", "root","Rojo2001.");

            String comando_update = "UPDATE t_paises SET  pais=?, tipo = ?,precio = ?, fecha = ? WHERE id = ?";

            PreparedStatement comandoPreparado = nuevaConexion.prepareStatement(comando_update);

            // comandoPreparado.setString(1,txtIDActualizar.getText());
            comandoPreparado.setString(1, txtPaisAgregar.getText());
            comandoPreparado.setString(2, (String) cboxTipoAgregar.getSelectedItem());
            comandoPreparado.setDouble(3, Double.parseDouble(txtPrecioAgregar.getText()));
            comandoPreparado.setString(4, txtFechaAgregar.getText());

            comandoPreparado.setInt(5,Integer.parseInt(txtIDActualizar.getText()));

            comandoPreparado.executeUpdate();

            int fila = Integer.parseInt(txtIDActualizar.getText());

            mt.setValueAt(txtPaisAgregar.getText(),fila-1,0 );
            mt.setValueAt((String) cboxTipoAgregar.getSelectedItem(),fila-1,1 );
            mt.setValueAt(Double.parseDouble(txtPrecioAgregar.getText()),fila-1,2 );
            mt.setValueAt(txtFechaAgregar.getText(),fila-1,3 );

            txtPaisAgregar.setText("");
            txtPrecioAgregar.setText("");
            txtFechaAgregar.setText("");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al conectar con la Base de Datos "+ex.getMessage());
        }

    }//GEN-LAST:event_btnActualizarPaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarPais;
    private javax.swing.JButton btnAgregarPais;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JComboBox<String> cboxTipoAgregar;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFechaAgregar;
    private javax.swing.JLabel lblPaisAgregar;
    private javax.swing.JLabel lblPrecioAgregar;
    private javax.swing.JLabel lblTipoAgregar;
    private javax.swing.JTextField txtFechaAgregar;
    private javax.swing.JTextField txtIDActualizar;
    private javax.swing.JTextField txtPaisAgregar;
    private javax.swing.JTextField txtPrecioAgregar;
    // End of variables declaration//GEN-END:variables
}
